# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-runner"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Command runner for rsjudge"

[dependencies]
async-trait = "0.1.80"
capctl = "0.2.4"
cgroups-rs = "0.3.4"
libseccomp = { version = "0.3.0", features = ["const-syscall"] }
log.workspace = true
nix = { version = "0.28.0", features = ["user", "resource"] }
rsjudge-utils.workspace = true
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["process", "sync", "time"] }
tokio-util = "0.7.11"
uzers = "0.12.0"

[dev-dependencies]
anyhow = "1.0.82"

[build-dependencies]
rustversion = "1.0.17"
