[package]
name = "rsjudge-runner"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Command runner for rsjudge"

[dependencies]
anyhow = "1.0.81"
caps = "0.5.5"
nix = { version = "0.28.0", features = ["user"] }
once_cell = "1.19.0"
uzers = "0.11.3"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
rsjudge-utils = { path = "../rsjudge-utils" }
