# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-runner"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Command runner for rsjudge"

[dependencies]
caps = "0.5.5"
log.workspace = true
nix = { version = "0.28.0", features = ["user"] }
rsjudge-utils.workspace = true
thiserror = "1.0.58"
uzers = "0.11.3"

[build-dependencies]
rustc_version = "0.4.0"

[dev-dependencies]
anyhow = "1.0.81"
