[package]
name = "rsjudge-runner"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "Command runner for rsjudge"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
nix = { version = "0.28.0", features = ["user"] }
once_cell = "1.19.0"
uzers = "0.11.3"
