# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
log.workspace = true
shell-words = "1.1.0"

[dev-dependencies]
trybuild = "1.0.91"
