[workspace]
members = ["crates/rsjudge-grpc", "crates/rsjudge-rest", "crates/rsjudge-runner", "xtask"]

[workspace.package]
version = "0.1.0"
authors = ["NJUPT-SAST"]
license = "Apache-2.0"

[package]
name = "rsjudge"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true
description = "An online judge sandbox server in Rust."

[package.metadata.deb]
assets = [
    [
        "target/release/rsjudge",
        "usr/bin/rsjudge",
        "755",
    ],
    [
        "templates/executors.toml",
        "etc/rsjudge/executors.toml",
        "644",
    ],
    [
        "templates/server.toml",
        "etc/rsjudge/server.toml",
        "644",
    ],
    [
        "target/release/out/rsjudge.1",
        "usr/share/man/man1/rsjudge.1",
        "644",
    ],
    [
        "README.adoc",
        "usr/share/doc/rsjudge/README",
        "644",
    ],
    [
        "target/release/out/rsjudge.bash",
        "usr/share/bash-completion/completions/rsjudge",
        "644",
    ],
    [
        "target/release/out/rsjudge.fish",
        "usr/share/fish/vendor_completions.d/rsjudge.fish",
        "644",
    ],
    [
        "target/release/out/_rsjudge",
        "usr/share/zsh/vendor-completions/_rsjudge",
        "644",
    ],
]
copyright = "2023-2024 NJUPT-SAST"
features = ["default"]
conf-files = ["/etc/rsjudge/server.toml", "/etc/rsjudge/executors.toml"]
maintainer-scripts = "debian/"
depends = "$auto, libc6, libgcc-s1, libstdc++6, libssl1.1, libzstd1, libzstd-dev"
recommends = "gcc, g++, python3"
suggests = "pypy3"
systemd-units = { enable = false }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Workspace dependencies
rsjudge-runner = { version = "0.1.0", path = "crates/rsjudge-runner" }

# Optional dependencies
rsjudge-grpc = { version = "0.1.0", path = "crates/rsjudge-grpc", optional = true }
rsjudge-rest = { version = "0.1.0", path = "crates/rsjudge-rest", optional = true }

anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["fs", "rt-multi-thread", "macros"] }
toml = "0.8.10"
log = "0.4.20"
env_logger = "0.11.2"

# Unused for now:
# cgroups = "0.1.0"
# duct = "0.13.7"
# nix = { version = "0.27.1", features = ["fs"] }
# strfmt = "0.2.4"
# uzers = "0.11.3"

[dev-dependencies]
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }

[features]
grpc = ["dep:rsjudge-grpc"]
rest = ["dep:rsjudge-rest"]
default = ["grpc"]

[build-dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
clap_complete = "4.5.1"
clap_mangen = "0.2.20"

[profile.release]
codegen-units = 1
lto = true
strip = true
