[package]
name = "rsjudge"
description = "An online judge sandbox server in Rust."
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["NJUPT-SAST"]

[package.metadata.deb]
assets = [
    [
        "target/release/rsjudge",
        "/usr/bin/rsjudge",
        "755",
    ],
    [
        "templates/executors.toml",
        "/etc/rsjudge/executors.toml",
        "644",
    ],
    [
        "templates/server.toml",
        "/etc/rsjudge/server.toml",
        "644",
    ],
]
maintainer-scripts = "debian/"
depends = "$auto, libc6, libgcc-s1, libstdc++6, libssl1.1, libzstd1, libzstd-dev"
recommends = "gcc, g++, openjdk-17-jdk-headless, openjdk-21-jdk-headless, pypy3, python3"
suggests = ""
systemd-units = { enable = false }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.2"
cgroups = "0.1.0"
serde = { version = "1.0.193", features = ["derive"] }
strfmt = "0.2.4"
tokio = { version = "1.35.0", features = ["fs"] }
toml = "0.8.8"

# Optional dependencies
tonic = { version = "0.10.2", optional = true }
utoipa = { version = "4.1.0", features = ["axum_extras"], optional = true }
utoipa-swagger-ui = { version = "5.0.0", features = ["axum"], optional = true }

[dev-dependencies]
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros"] }

[features]
grpc = ["dep:tonic"]
openapi = ["dep:utoipa", "dep:utoipa-swagger-ui"]
default = ["grpc", "openapi"]
