# SPDX-License-Identifier: Apache-2.0

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-DFS-2016",
]

[[bans.skip-tree]]
crate = "libcgroups@0.3.3"
reason = "libcgroups 0.3.3 ships with nix 0.27, see upstream https://github.com/containers/youki/pull/2791"

[[bans.skip-tree]]
crate = "petgraph@0.6.5"
reason = "petgraph 0.6.5 ships with fixedbitset 0.4.2, see upstream https://github.com/petgraph/petgraph/pull/617"

[[bans.skip-tree]]
crate = "axum-core@0.4.3"
reason = "axum 0.7.5 depends on sync_wrapper 1.0, but it also depends on axum-core 0.4.3, which depends on sync_wrapper 0.1.1"
