[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]

[[bans.skip]]
crate = "heck@0.4.1"
reason = "Upstream https://github.com/tokio-rs/prost/issues/1009"

[[bans.skip-tree]]
crate = "tonic@0.11.0"
reason = "tonic 0.11.0 is not compatible with tokio 1.0"
