# SPDX-License-Identifier: Apache-2.0

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[[bans.skip-tree]]
crate = "libcgroups@0.4.1"
reason = "libcgroups 0.4.1 ships with nix 0.28, see upstream https://github.com/containers/youki/pull/2791"

[[bans.skip-tree]]
crate = "tower@0.4.13"
reason = "axum 0.7.5 depends on tower 0.4 and transitively on tower 0.5, see upstream https://github.com/tokio-rs/axum/pull/2880"
