# SPDX-License-Identifier: Apache-2.0

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[[bans.skip-tree]]
crate = "bitflags@1.3.2"
reason = """
confirmed, not fixed: https://github.com/cptpcrd/capctl/issues/3

fixed, not released: https://github.com/libseccomp-rs/libseccomp-rs/pull/238

bitflags v1.3.2
├── capctl v0.2.4
│   └── rsjudge-runner v0.1.0 (/home/jswn/rsjudge/crates/rsjudge-runner)
│       └── rsjudge v0.1.0 (/home/jswn/rsjudge)
└── libseccomp v0.3.0
    └── rsjudge-runner v0.1.0 (/home/jswn/rsjudge/crates/rsjudge-runner) (*)
"""

[[bans.skip-tree]]
crate = "indexmap@1.9.3"
reason = """
fixed, not released: https://github.com/hyperium/tonic/pull/1892

indexmap v1.9.3
└── tower v0.4.13
    └── tonic v0.12.3
        └── rsjudge-grpc v0.1.0 (/home/jswn/rsjudge/crates/rsjudge-grpc)
            └── rsjudge v0.1.0 (/home/jswn/rsjudge)
"""

[[bans.skip-tree]]
crate = "axum@0.7.9"
reason = """
fixed, not released: https://github.com/hyperium/tonic/pull/1975

axum v0.7.9
└── tonic v0.12.3
    └── rsjudge-grpc v0.1.0 (/home/jswn/rsjudge/crates/rsjudge-grpc)
        └── rsjudge v0.1.0 (/home/jswn/rsjudge)
"""
