# SPDX-License-Identifier: Apache-2.0

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[[bans.skip-tree]]
crate = "bitflags@1.3.2"
reason = """
confirmed, not fixed: https://github.com/cptpcrd/capctl/issues/3

bitflags v1.3.2
└── capctl v0.2.4
    └── rsjudge-runner v0.1.0 (rsjudge/crates/rsjudge-runner)
        └── rsjudge v0.1.0 (rsjudge)
"""
