= rsjudge
:toc: preamble
:source-highlighter: rouge

An online judge sandbox server in Rust, inspired by https://github.com/criyle/go-judge[go-judge], for SAST OJ.

== Features

* Supports multiple programming languages, with easy way to add new ones in config file.
* Support for multiple compiler versions -- just use your favorite toolchain manager and set the path in config file.
* Supporting both self-testing and final submission.
* Customizable compilation and execution process with TOML config file.
* Monitoring and limiting resource usage.
* Asynchronously report test results.
* Works well with SAST OJ.
* RESTful API and gRPC support, enable or disable them with feature flags and config file.
* Highly extensible with plugins.
* Blazingly fast and secured with Rust🦀.

== Repository structure

`src/`::
    Source of entry point, including CLI and configuration parsing.
`xtask/`::
    Extra tasks for building and packaging, invoked with `cargo xtask <TASK>`.
`crates/`::
    Sub-crates of the project.
    `crates/rsjudge-grpc/`:::
        Crate for gRPC server and client.
    `crates/rsjudge-judger/`:::
        Crate for answer comparing and judging.
    `crates/rsjudge-rest/`:::
        Crate for RESTful API server.
    `crates/rsjudge-runner/`:::
        Crate for sandbox logic.
`debian/`::
    Files for generating `.deb` package.

https://mango-dune-07a8b7110.1.azurestaticapps.net/?repo=NJUPT-SAST%2Frsjudge[
    image:https://github.com/NJUPT-SAST/rsjudge/raw/diagram/diagram.svg[
        Repository structure visualized
    ]
]

== Build from source

=== Prerequisites

* Rust 1.74 or later.
* `lld` for faster linking.
** You can use other linkers instead, just update the `.cargo/config.toml` file.
* Linux kernel >= 4.5
** This is required for Seccomp BPF support.
* For gRPC support, the `protoc` Protocol Buffers compiler, along with Protocol Buffers resource files (under `grpc` feature)
* For `.deb` package generation, a Debian/Ubuntu system with `dpkg-dev` and `liblzma-dev` installed.

=== Install extra dependencies

==== Debian/Ubuntu

[,bash]
----
sudo apt install -y lld protobuf-compiler libprotobuf-dev

# If you want to build `.deb` package
sudo apt install -y dpkg-dev liblzma-dev
----

==== Alpine

[,bash]
----
sudo apk add lld protoc protobuf-dev
----

==== Arch Linux

[,bash]
----
sudo pacman -S --needed lld protobuf
----

=== Build

Clone the repository:

[,bash]
----
git clone https://github.com/NJUPT-SAST/rsjudge.git
cd rsjudge
----

Build the project with Cargo:

[,bash]
----
cargo build --release
----

Generate `.deb` package:

[,bash]
----
cargo xtask dist deb
----
