= RsJudge
:toc: preamble

An online judge sandbox server in Rust, inspired by https://github.com/criyle/go-judge[go-judge], for SAST OJ.

== Features

* Multi-language support
* Support for multiple compiler versions -- use your favorite toolchain manager and set the path in config file
* Supporting both self-testing and final submission
* Customizable compilation and execution command with TOML config file
* Customizable time and memory limit using cgroups
* Asynchronously report test results
* Fully supporting SAST OJ
* RESTful API and gRPC support
* Highly extensible with plugins
* Blazingly fast and secured with Rust🦀

== Build from source

=== Prerequisites

* Rust latest stable toolchain
* Linux kernel >= 4.5
* `asciidoctor` to generate manpages
* `dpkg`, `dpkg-dev` and `liblzma-dev` to generate `.deb` package
* For gRPC support, the `protoc` Protocol Buffers compiler, along with Protocol Buffers resource files (under `grpc` feature):

==== Debian/Ubuntu
[,bash]
----
sudo apt install -y protobuf-compiler libprotobuf-dev
----

==== Alpine
[,bash]
----
sudo apk add protoc protobuf-dev
----

==== Arch Linux
[,bash]
----
sudo pacman -S --needed protobuf
----

=== Build

Clone the repository:

[,bash]
----
git clone https://github.com/NJUPT-SAST/rsjudge.git
cd rsjudge
----

Build the project with Cargo:

[,bash]
----
cargo build --release
----

Generate `.deb` package:

[,bash]
----
cargo xtask dist deb
----
