= rsjudge
:toc: preamble

An online judge sandbox server in Rust, inspired by https://github.com/criyle/go-judge[go-judge], for SAST OJ.

== Features

* Supports multiple programming languages, with easy way to add new ones in config file.
* Support for multiple compiler versions -- just use your favorite toolchain manager and set the path in config file.
* Supporting both self-testing and final submission.
* Customizable compilation and execution process with TOML config file.
* Monitoring and limiting resource usage.
* Works well with SAST OJ.
* RESTful API and gRPC support, enable or disable them with feature flags and config file.
* Streaming test results in real-time with SSE or gRPC stream.
* Highly extensible with plugins.
* Blazingly fast and secured with Rust🦀.

== Repository structure

`src/`::
    Source of entry point, including CLI and configuration parsing.
`xtask/`::
    Extra tasks for building and packaging, invoked with `cargo xtask <TASK>`.
`crates/`::
    Sub-crates of the project.
    `crates/rsjudge-grpc/`:::
        Crate for gRPC server and client.
    `crates/rsjudge-judger/`:::
        Crate for answer comparing and judging.
    `crates/rsjudge-rest/`:::
        Crate for RESTful API server.
    `crates/rsjudge-runner/`:::
        Crate for sandbox logic.
`debian/`::
    Files for generating `.deb` package.

https://mango-dune-07a8b7110.1.azurestaticapps.net/?repo=NJUPT-SAST%2Frsjudge[
    image:https://github.com/NJUPT-SAST/rsjudge/raw/diagram/diagram.svg[
        Repository structure visualized
    ]
]

== Build from source

=== Prerequisites

* Rust 1.74 or later,
* `lld` for faster linking,
** You can use other linkers instead, just update the `.cargo/config.toml` file.
* Linux kernel >= 4.5,
** Required for Seccomp BPF support.
* For gRPC support (under `grpc` feature):
** `protoc` as Protocol Buffers compiler,
** `buf` for gRPC dependencies management.
* For `.deb` package generation, a Debian/Ubuntu system with `dpkg-dev` and `liblzma-dev` installed.

=== Install dependencies

==== Debian/Ubuntu

[,bash]
----
sudo apt install -y lld protobuf-compiler libprotobuf-dev

# For buf support
curl -sSL -o buf \
  "https://github.com/bufbuild/buf/releases/download/latest/buf-Linux-$(uname -m)"
# You may replace `/usr/local/bin` with your preferred directory，
# and ensure it is added to `PATH`.
sudo install -Dm755 buf /usr/local/bin/buf

# If you want to build `.deb` package
sudo apt install -y dpkg-dev liblzma-dev
----

==== Alpine

[,bash]
----
sudo apk add lld protoc protobuf-dev

# For buf support
curl -sSL -o buf \
  "https://github.com/bufbuild/buf/releases/download/latest/buf-Linux-$(uname -m)"
# Replace `/usr/local/bin` with your preferred directory,
# remember to add it to `PATH`
sudo install -Dm755 buf /usr/local/bin/buf
----

==== Arch Linux

[,bash]
----
sudo pacman -S --needed lld protobuf buf
----

=== Build

Clone the repository:

[,bash]
----
git clone https://github.com/NJUPT-SAST/rsjudge.git
cd rsjudge
----

Build the project with Cargo:

[,bash]
----
cargo build --release
----

Generate `.deb` package:

[,bash]
----
cargo xtask dist deb
----
