# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-traits"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.80"
indexmap = { version = "2.2.6", features = ["serde"] }
serde.workspace = true
tokio = { version = "1.37.0", features = ["process"] }

[dev-dependencies]
serde_json = "1.0.117"
toml = { version = "0.8.13", features = ["preserve_order"] }
