# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-traits"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.81"
indexmap = { version = "2.2.6", features = ["serde"] }
serde.workspace = true
tokio = { workspace = true, features = ["process"] }

[dev-dependencies]
serde_json = "1.0.121"
toml = { version = "0.8.15", features = ["preserve_order"] }
