# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-traits"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.80"
indexmap = { version = "2.2.6", features = ["serde"] }
serde.workspace = true
tokio = { version = "1.38.0", features = ["process"] }

[dev-dependencies]
serde_json = "1.0.120"
toml = { version = "0.8.14", features = ["preserve_order"] }
