[alias]
xtask = "run --package xtask --locked --"
xtask-dbg = "run --package xtask --features dbg --locked --"

[build]
# Use custom linker for faster linking
# rustflags = ["-Clink-arg=-fuse-ld=mold"]
build-dir = "build"
