# SPDX-License-Identifier: Apache-2.0

[C]
# Example $flags: "-O2 -std=c99"
message = "使用 $(gcc --version)。"
exec_type = "binary"
compile = "gcc {...flags} -lm -Wall -o {out_file} {src_file}"

[C.options.O2]
type = "bool"
target = "flags"
default = true
enable = "-O2"

[C.options.version]
type = "enum"
target = "flags"
default = "C99"

[C.options.version.variants]
C99 = "-std=c99"
C11 = "-std=c11"

["C++"]
# Example $flags: "-O2 -std=c++14"
exec_type = "binary"
compile = "g++ {...flags} -lm -Wall -o {out_file} {src_file}"

["C++".options.O2]
type = "bool"
target = "flags"
default = true
enable = "-O2"

["C++".options.version]
type = "enum"
target = "flags"
default = "C++17"

["C++".options.version.variants]
"C++98" = "-std=c++98"
"C++11" = "-std=c++11"
"C++14" = "-std=c++14"
"C++17" = "-std=c++17"
"C++20" = "-std=c++20"

["C#"]
# Only mono is supported now, .NET SDK is under development.
exec_type = "byte_code"
out_rename = "Program.exe"
compile = "mcs -o+ -out:{out_file} {src_file}"
execute = "mono {out_file}"

[Dart]
# Install Dart SDK as described in https://dart.dev/get-dart
exec_type = "binary"
compile = "dart compile exe -o {out_file} {src_file}"

[Go]
exec_type = "binary"
compile = "go build -o {out_file} {src_file}"

[Java]
exec_type = "byte_code"
message = """
Java 版本：

```
$(java --version)
```
"""
src_rename = "Main.java"
out_extension = "jar"
compile = "javac -d {tmp_dir} Main.java && jar -cvfe {out_file} Main -C {tmp_dir} *"
execute = "java -jar {out_file}"

[JavaScript]
exec_type = "source_code"
message = "使用 Node.js $(node -v)。"
check = "node -c {src_file}"
execute = "node {src_file}"

[Kotlin]
exec_type = "byte_code"
out_extension = "jar"
compile = "kotlinc -include-runtime -d {out_file} {src_file}"
execute = "java -jar {out_file}"

[Python]
# -S: do not import site
# TODO: Use virtualenv to isolate the environment.
exec_type = "source_code"
message = "使用 $(python3 -V)。"
check = "python3 -m py_compile {src_file}"
execute = "python3 -I -S {src_file}"

[Ruby]
exec_type = "source_code"
check = "ruby -c {src_file}"
execute = "ruby {src_file}"

[Rust]
exec_type = "binary"
message = "使用 $(rustc --version)。"
compile = "rustc -O -o {out_file} {src_file}"

[TypeScript]
exec_type = "byte_code"
message = "使用 TypeScript $(tsc -v)、Node.js $(node -v)。"
compile = "tsc {src_file} --outFile {out_file}"
execute = "node {out_file}"

[Swift]
exec_type = "binary"
compile = "swiftc -o {out_file} {src_file}"

[Zig]
exec_type = "binary"
compile = "zig build-exe -femit-bin={out_file} {src_file}"
