# SPDX-License-Identifier: Apache-2.0

[grpc]
listen = [
    "0.0.0.0:50051",
    "[::]:50051",
]

[rest]
listen = [
    "0.0.0.0:80",
    "[::]:80",
]

[rabbitmq]
uri = "amqp://user:bitnami@localhost"
