#!/bin/sh
set -e

RSJUDGE_CONF="/etc/rsjudge/*.conf"

case "$1" in
purge)
    if [ -f "${RSJUDGE_CONF}" ]; then
        rm "${RSJUDGE_CONF}"
    fi

    deluser --system --remove-home --group "${RSJUDGE_USER}-supervisor" || true
    deluser --system --remove-home --group "${RSJUDGE_USER}-builder" || true
    deluser --system --remove-home --group "${RSJUDGE_USER}-runner" || true

    ;;
esac

#DEBHELPER#
