[package]
name = "rsjudge-grpc"
version.workspace = true
authors.workspace = true
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.11.0"

[build-dependencies]
anyhow = "1.0.79"
tonic-build = "0.11.0"
