[package]
name = "rsjudge-grpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.79"
prost = "0.12.3"
tokio = { version = "1.36.0", features = ["net"] }
tokio-stream = "0.1.14"
tonic = "0.11.0"
[build-dependencies]
anyhow = "1.0.79"
tonic-build = "0.11.0"
