# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-grpc"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "gRPC server for rsjudge"

[package.metadata.cargo-machete]
ignored = ["prost", "prost-types"]

[dependencies]
anyhow = "1.0.82"
futures = "0.3.30"
log.workspace = true
prost = "0.12.4"
prost-types = "0.12.4"
tokio = { version = "1.37.0", features = ["net"] }
tokio-stream = "0.1.15"
tonic = "0.11.0"

# Optional dependencies
serde = { version = "1.0.198", optional = true, features = ["derive"] }
axum = "0.7.5"
rsjudge-traits = { version = "0.1.0", path = "../rsjudge-traits" }

[build-dependencies]
anyhow = "1.0.82"
rsjudge-utils.workspace = true
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "process"] }
tonic-build = "0.11.0"

[features]
serde = ["dep:serde"]
