# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-amqp"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
amqprs = { version = "1.6.2", features = ["urispec"] }
thiserror = "1.0.62"
tokio = "1.38.0"

rsjudge-traits.workspace = true
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
