name: benchmark

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y wget clang
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          components: rust-src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup protoc
        uses: Noelware/setup-protoc@1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.4
      - name: Enable sccache
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - name: Run criterion benchmarks
        run: cargo bench --workspace
      - name: Upload benchmark result to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-result
          path: target/criterion
