name: testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: moonrepo/setup-rust@v1
        with:
          channel: stable
          bins: cargo-deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y && \
          sudo apt install -y asciidoctor protobuf-compiler libprotobuf-dev
      - name: Build manpages
        run: asciidoctor -b manpage --safe docs/manpages/*.adoc
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Build Debian package
        run: cargo xtask dist deb && dpkg-deb -c target/debian/*.deb
      - uses: actions/upload-artifact@v4
        with:
          name: rsjudge-deb
          path: target/debian/*.deb
