# SPDX-License-Identifier: Apache-2.0

[package]
name = "rsjudge-judger"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.78"
futures = "0.3.30"
rsjudge-utils = { version = "0.1.0", path = "../rsjudge-utils" }
tokio = { version = "1.36.0", features = ["io-util", "fs", "macros"] }

[dev-dependencies]
temp-dir = "0.1.12"
tokio = { version = "1.36.0", features = ["rt-multi-thread"] }
